Repository estuary/marketing-site, pull requests merged in 2025-03, with the labels that each got.

#718 Fix social preview image from success story page
  src/templates/success-story/Head/index.tsx
  src/templates/success-story/index.tsx
Labels: bug, generate-pr-preview

#722 Fix solutions menu not totally visible
  src/components/Header/index.tsx
  src/components/Header/styles.module.less
  src/components/HeaderNavbar/Card/styles.module.less
  src/components/HeaderNavbar/CardItem/styles.module.less
  src/components/HeaderNavbar/Product/items.tsx
  src/components/HeaderNavbar/Resources/index.tsx
  src/components/HeaderNavbar/Resources/items.tsx
  src/components/HeaderNavbar/shared.ts
  src/components/HeaderNavbar/styles.module.less
Labels: bug, enhancement, generate-pr-preview

#725 Fix success stories displaying 404 from all success stories page
  src/components/BlogPopularArticles/index.tsx
  src/components/EtlToolsPage/LearnMoreArticles/index.tsx
  src/components/Grid/Card/index.tsx
  src/components/SuccessStoriesPage/SuccessStories/index.tsx
  src/templates/author/SectionTwo/index.tsx
Labels: bug

#717 Blog sidebar rework
  src/components/ArticleSidebar/index.tsx
  src/components/ArticleSidebar/styles.module.less
  src/components/BlogPost/index.tsx
  src/components/BlogPostToc/index.tsx
  src/components/BlogPostToc/styles.module.less
  src/components/Header/index.tsx
  src/components/HeaderNavbar/index.tsx
  src/components/HeaderNavbar/styles.module.less
  src/components/ShareArticle/styles.module.less
  src/components/SidebarCta/index.tsx
  src/components/SidebarCta/styles.module.less
  src/images/build-pipeline.svg
  src/images/pattern-sidebar-cta.svg
Labels: enhancement, generate-pr-preview

#728 Fix spacing on success story page
  src/templates/success-story/styles.module.less
Labels: enhancement

#730 Add Ecommerce to Industry Solutions in Navbar
  src/components/HeaderNavbar/Solutions/items.tsx
Labels: generate-pr-preview

#727 `build` and `deps` - trying to improve memory a bit
  gatsby-config.ts
  gatsby-node.ts
  package.json
  yarn.lock
Labels: generate-pr-preview

#731 Replace homepage Flow diagram
  src/components/CompanyUpdatesPage/Hero/FlowDiagram/index.tsx
  src/components/CompanyUpdatesPage/Hero/FlowDiagram/styles.module.less
  src/components/CompanyUpdatesPage/Hero/index.tsx
  src/components/CompanyUpdatesPage/Hero/styles.module.less
  src/components/FlowDiagram/index.tsx
  src/components/FlowDiagram/styles.module.less
  src/images/company-updates/hero-image.png
  src/images/company-updates/move-and-transform-data.png
  src/images/homepage/move-and-transform-data-mobile.png
  src/images/homepage/move-and-transform-data.png
  src/svgs/company-updates-flow-diagram/ai.svg
  src/svgs/company-updates-flow-diagram/analytics.svg
  src/svgs/company-updates-flow-diagram/batch.svg
  src/svgs/company-updates-flow-diagram/ops.svg
  src/svgs/company-updates-flow-diagram/real-time.svg
  src/svgs/company-updates-flow-diagram/saas.svg
  src/svgs/company-updates-flow-diagram/store.svg
  src/svgs/company-updates-flow-diagram/transform.svg
Labels: enhancement, generate-pr-preview

#735 Add Healthcare to Industry Solutions in Navigation Menu
  src/components/HeaderNavbar/CardItem/index.tsx
  src/components/HeaderNavbar/Solutions/items.tsx
Labels: generate-pr-preview

#740 Replace current blog post pop-up banner
  src/components/BackgroundImages/LightSwoopingLinesRightDirectionBackground.tsx
  src/components/BlogPost/index.tsx
  src/components/BlogPostPopupModal/index.tsx
  src/components/BlogPostPopupModal/styles.module.less
  src/components/CompanyUpdatesPage/Hero/FlowDiagram/index.tsx
Labels: enhancement, generate-pr-preview

#742 Reverse sort order success stories on homepage and success stories page
  shared.ts
  src/components/Homepage/SuccessStories/index.tsx
  src/components/SuccessStoriesPage/SuccessStories/index.tsx
Labels: enhancement

#743 Centralize horizontally the blog post images
  src/style.less
Labels: enhancement, generate-pr-preview

#756 Adjust comparison text on vendor pricing heading
  src/components/EtlToolsXvsYPage/Comparison/IntroductoryDetails/index.tsx
  src/components/EtlToolsXvsYPage/Comparison/index.tsx
Labels: enhancement
