Repository estuary/marketing-site, pull requests merged in 2025-02, with the labels that each got.

#661 New homepage updates
  src/components/Header/styles.module.less
  src/components/HeaderNavbar/Card/styles.module.less
  src/components/HeaderNavbar/styles.module.less
  src/components/HeroSectionDetails/styles.module.less
  src/components/Homepage/Hero/styles.module.less
  src/components/Layout/ReleaseBanner/styles.module.less
  src/components/Layout/styles.module.less
  src/components/MetricCard/styles.module.less
  src/pages/index.tsx
  src/pages/solutions/styles.module.less
  src/style.less
Labels: enhancement

#668 Remove full uppercase from blog post and success story titles
  src/components/BlogPost/styles.module.less
  src/templates/success-story/styles.module.less
Labels: enhancement

#667 Remove icon from section
  src/components/Homepage/Do4xMoreWith25xLess/index.tsx
  src/components/Homepage/TheBestRealTimeCdc/index.tsx
Labels: enhancement

#663 Comparison matrix improvements
  gatsby-config.ts
  shared.ts
  src/components/EtlToolsXvsYPage/Comparison/Connectors/index.tsx
  src/components/EtlToolsXvsYPage/Comparison/CoreFeatures/index.tsx
  src/components/EtlToolsXvsYPage/Comparison/Cost/index.tsx
  src/components/EtlToolsXvsYPage/Comparison/DeploymentOptions/index.tsx
  src/components/EtlToolsXvsYPage/Comparison/IntroductoryDetails/index.tsx
  src/components/EtlToolsXvsYPage/Comparison/Security/index.tsx
  src/components/EtlToolsXvsYPage/Comparison/Support/index.tsx
  src/components/EtlToolsXvsYPage/Comparison/TableRows/index.tsx
  src/components/EtlToolsXvsYPage/Comparison/TableRows/styles.module.less
  src/components/EtlToolsXvsYPage/Comparison/UseCases/index.tsx
  src/components/EtlToolsXvsYPage/Comparison/VendorAvatar/styles.module.less
  src/components/EtlToolsXvsYPage/Comparison/index.tsx
  src/components/EtlToolsXvsYPage/Comparison/styles.module.less
  src/components/Header/index.tsx
  src/components/HeaderNavbar/Background.tsx
  src/components/HeaderNavbar/index.tsx
  src/components/Layout/index.tsx
  src/templates/etl-tools/index.tsx
Labels: enhancement

#679 update workflow `cache` version
  .github/workflows/deploy-preview.yml
  .github/workflows/deploy-prod.yml
Labels: dependencies

#681 Update some slugs from solution menu links
  src/components/HeaderNavbar/Solutions/items.tsx
Labels: bug

#683 Replace hardcoded text from key features section
  src/components/Solutions/Sections/KeyFeatures/Card/styles.module.less
  src/components/Solutions/Sections/KeyFeatures/index.tsx
  src/components/Solutions/Sections/KeyFeatures/styles.module.less
  src/components/Solutions/Tag/index.tsx
  src/components/Solutions/Tag/styles.module.less
Labels: bug, enhancement

#686 Updated to Github workflow
  .github/workflows/deploy-preview.yml
  .github/workflows/deploy-prod.yml
Labels: generate-pr-preview

#687 Upgrade `gatsby` to latest
  .github/workflows/deploy-preview.yml
  .gitignore
  .lighthouserc.js
  gatsby-node.ts
  package.json
  yarn.lock
Labels: generate-pr-preview

#691 Replace innovate section on homepage
  gatsby-node.ts
  src/components/Homepage/InnovateFaster/index.tsx
  src/components/Homepage/InnovateFaster/styles.module.less
  src/components/Homepage/SecureDataMovement/ConnectorsMasonry/index.tsx
  src/components/Homepage/SecureDataMovement/ConnectorsMasonry/styles.module.less
  src/components/Homepage/SecureDataMovement/index.tsx
  src/components/Homepage/SecureDataMovement/styles.module.less
  src/images/apache-iceberg-logo.png
  src/images/apache-kafka-logo.png
  src/images/facebook-ads-logo.png
  src/images/google-ads-logo.png
  src/images/http-webhooks-logo.png
  src/images/hubspot-logo.png
  src/images/microsoft-fabric-warehouse-logo.png
  src/images/motherduck-logo.png
  src/images/ms-sql-server-logo.png
  src/images/netsuite-logo.png
  src/images/oracle-logo.png
  src/images/salesforce-logo.png
  src/images/shopify-logo.png
  src/images/tinybird-logo.png
  src/images/trusted-partner-badges/ai-data-cloud-products-snowflake-partner.png
  src/images/trusted-partner-badges/databricks-technology-partner-validated.png
  src/pages/etl-tools/index.tsx
  src/pages/index.tsx
  src/templates/etl-tools/index.tsx
Labels: enhancement

#700 Update pricing calculator
  src/components/Homepage/SecureDataMovement/ConnectorsMasonry/index.tsx
  src/components/PricingCalculator/ComparisonCard.tsx
  src/components/PricingCalculator/index.tsx
  src/components/PricingCalculator/styles.module.less
Labels: enhancement, generate-pr-preview

#690 Add preview image to vendor comparison template pages
  src/images/vendor-comparison.png
  src/templates/etl-tools/Head/index.tsx
  src/templates/etl-tools/index.tsx
Labels: enhancement, generate-pr-preview

#699 Filter `connectors` better and make connector search page safer
  gatsby-config.ts
  package.json
  src/components/Connectors/index.tsx
  src/components/ConnectorsLink/index.tsx
  src/templates/connection.tsx
  src/templates/connector/Hero/index.tsx
  src/templates/connector/index.tsx
  src/utils.ts
  yarn.lock
Labels: generate-pr-preview

#695 Make blog post search better
  gatsby-config.ts
  gatsby-node.ts
  package.json
  src/templates/blog/index.tsx
  yarn.lock
Labels: generate-pr-preview

#710 Fix pricing calculator responsiveness
  src/components/PricingCalculator/styles.module.less
Labels: bug

#705 Solution menu links should be capitalized
  src/components/HeaderNavbar/Solutions/items.tsx
Labels: enhancement

#708 Solve build failing due to connectors null logo
  src/components/ConnectorLogoPlaceholder/index.tsx
  src/components/Connectors/index.tsx
  src/components/ConnectorsLink/index.tsx
  src/components/Homepage/Hero/styles.module.less
  src/components/Integration/FromConnector/index.tsx
  src/components/Integration/Hero/index.tsx
  src/components/Integration/ToConnector/index.tsx
  src/components/Integration/shared.ts
  src/components/XvsYFilter/index.tsx
  src/svgs/connector-logo-placeholder.svg
  src/svgs/server.svg
  src/templates/connection.tsx
  src/templates/connector/Hero/index.tsx
  src/templates/connector/Hero/styles.module.less
  src/templates/connector/index.tsx
Labels: bug, generate-pr-preview
