Repository estuary/marketing-site, pull requests merged in 2025-07, with the labels that each got.

#890 Replace text logo with full image logo on footer
  src/components/Footer/index.tsx
  src/components/Footer/styles.module.less
  src/images/brand-guidelines-page/estuary-logos/estuary-logo-color-on-dark.png
  src/images/brand-guidelines-page/estuary-logos/estuary-logo-color-on-light.png
  src/images/brand-guidelines-page/estuary-logos/estuary-logo-mono-on-dark.png
  src/images/brand-guidelines-page/estuary-logos/estuary-logo-mono-on-light.png
  src/images/estuary-icon.png
  src/images/estuary-text-logo.png
Labels: enhancement

#889 Add related success story banner to blog post left sidebar
  gatsby-config.ts
  src/components/ArticleSidebar/styles.module.less
  src/components/BlogPost/index.tsx
  src/components/BlogPost/styles.module.less
  src/templates/blog-post/index.tsx
Labels: enhancement, generate-pr-preview

#884 New tech solutions page for snowflake
  .env.example
  .gitignore
  README.md
  gatsby-config.ts
  gatsby-node.ts
  shared.ts
  src/components/BenchmarkPage/KeyHighlights/index.tsx
  src/components/BlogPost/index.tsx
  src/components/Carousel/index.tsx
  src/components/Carousel/styles.module.less
  src/components/FlowDemoVideo/index.tsx
  src/components/Grid/Card/index.tsx
  src/components/Grid/Card/styles.module.less
  src/components/HeaderNavbar/Solutions/items.tsx
  src/components/HeroSectionActions/ContactUsCta.tsx
  src/components/HeroSectionActions/RegisterCta.tsx
  src/components/HeroSectionActions/index.tsx
  src/components/Homepage/BuildInMinutes/index.tsx
  src/components/HtmlProcessor/index.tsx
  src/components/Integration/EstuaryFlowVideo/index.tsx
  src/components/ProductPage/CreateADataPipelineInMinutes/index.tsx
  src/components/Solutions/Card/styles.module.less
  src/components/Solutions/List/index.tsx
  src/components/Solutions/List/styles.module.less
  src/components/Solutions/SectionTitle/index.tsx
  src/components/Solutions/Sections/Benefits/index.tsx
  src/components/Solutions/Sections/ButtonsSection/index.tsx
  src/components/Solutions/Sections/ButtonsSection/styles.module.less
  src/components/Solutions/Sections/Capabilities/index.tsx
  src/components/Solutions/Sections/Capabilities/styles.module.less
  src/components/Solutions/Sections/CarouselSection/index.tsx
  src/components/Solutions/Sections/CarouselSection/styles.module.less
  src/components/Solutions/Sections/GraphicSection/index.tsx
  src/components/Solutions/Sections/GraphicSection/styles.module.less
  src/components/Solutions/Sections/Hero/index.tsx
  src/components/Solutions/Sections/Hero/styles.module.less
  src/components/Solutions/Sections/Highlights/index.tsx
  src/components/Solutions/Sections/Highlights/styles.module.less
  src/components/Solutions/Sections/KeyFeatures/index.tsx
  src/components/Solutions/Sections/OneTitleThreeCards/Card/index.tsx
  src/components/Solutions/Sections/OneTitleThreeCards/Card/styles.module.less
  src/components/Solutions/Sections/OneTitleThreeCards/index.tsx
  src/components/Solutions/Sections/OneTitleThreeCards/styles.module.less
  src/components/Solutions/Sections/Testimonial/index.tsx
  src/components/Solutions/TextCardsList/index.tsx
  src/components/Solutions/TextCardsList/styles.module.less
  src/components/TestimonialsCarousel/TestimonialSlide/styles.module.less
  src/components/Video/index.tsx
  src/components/Video/styles.module.less
  src/pages/about/index.tsx
  src/style.less
  src/templates/solutions/Head/index.tsx
  src/templates/solutions/industry/index.tsx
  src/templates/solutions/shared.ts
  src/templates/solutions/solution-page-layout/index.tsx
  src/templates/solutions/technology/index.tsx
  src/templates/solutions/use-cases/index.tsx
  src/templates/success-story/Sections/Body.tsx
  src/templates/success-story/Sections/Content.tsx
Labels: enhancement, generate-pr-preview

#892 Fix critical and high-severity security vulnerabilities
  package.json
  yarn.lock
Labels: generate-pr-preview

#895 Fix blog banner alt text issue
  src/templates/blog-post/index.tsx
Labels: bug

#897 firebase.json: set up redirect for openid-configuration
  firebase.json
Labels: generate-pr-preview

#899 Add benchmark banner to homepage hero section
  src/components/Layout/ReleaseBanner/index.tsx
  src/pages/index.tsx
Labels: enhancement

#901 Redirect to OpenID configuration
  firebase.json
Labels: generate-pr-preview

#902 Restructure the benchmark report page so the form is quickly seen
  src/components/BenchmarkPage/GetTheReport/index.tsx
  src/components/BenchmarkPage/GetTheReport/styles.module.less
  src/components/BenchmarkPage/Hero/index.tsx
  src/components/BenchmarkPage/Hero/styles.module.less
  src/pages/data-warehouse-benchmark-report/index.tsx
Labels: enhancement

#905 revert openid rewrites
  firebase.json
Labels: generate-pr-preview

#907 Add case study card for vanity logos
  src/components/Homepage/Hero/index.tsx
  src/components/Homepage/Hero/styles.module.less
  src/components/Integration/Hero/index.tsx
  src/components/VanityLogosMarquee/index.tsx
  src/components/VanityLogosMarquee/styles.less
Labels: enhancement, generate-pr-preview

#910 Fix TOC and blog cards styles
  src/components/BlogPostToc/styles.module.less
  src/templates/blog/styles.module.less
Labels: bug

#911 Fix broken list styles on About page
  src/pages/about/styles.module.less
Labels: bug

#912 Fix broken list styles
  src/components/BlogPostToc/styles.module.less
  src/components/DeploymentOptions/DeploymentOptionDetails/styles.module.less
  src/components/HtmlProcessor/index.tsx
  src/components/HtmlProcessor/styles.less
  src/components/MetricCardsList/index.tsx
  src/components/MetricCardsList/styles.module.less
  src/pages/about/styles.module.less
  src/style.less
  src/templates/blog/styles.module.less
Labels: bug

#914 Make some strapi seed data adaptations
  gatsby-node.ts
  src/components/ProductPage/KeyFeatures/features.tsx
  src/pages/etl-tools/index.tsx
Labels: tech debt, content

#918 Comment out Forward case study
  firebase.json
  shared.ts
  src/components/HeaderNavbar/Resources/index.tsx
  src/components/SuccessStoriesSection/index.tsx
  src/components/TestimonialsCarousel/utils.ts
Labels: enhancement
