Repository estuary/marketing-site, pull requests merged in 2025-04, with the labels that each got.

#754 Testing experimental cache option
  .github/workflows/deploy-preview.yml
  .github/workflows/deploy-prod.yml
  gatsby-config.ts
  gatsby-node.ts
  package.json
  src/components/BackgroundImages/WhyPageStepsBackground.tsx
  src/components/BlogPopularArticles/index.tsx
  src/components/BlogPost/index.tsx
  src/components/CompanyUpdatesPage/ListOfUpdates/index.tsx
  src/components/Grid/Card/index.tsx
  src/templates/author/index.tsx
  src/templates/blog-post/index.tsx
  src/templates/blog/index.tsx
  src/templates/company-update-post/index.tsx
  src/templates/success-story/index.tsx
  yarn.lock
Labels: generate-pr-preview

#755 Adjust the deployment option diagrams
  src/components/DeploymentOptions/DeploymentOptionDiagram/index.tsx
  src/components/DeploymentOptions/DeploymentOptionDiagram/styles.module.less
Labels: enhancement, generate-pr-preview

#757 Pricing table updates
  src/components/PricingPage/ChooseYourPlan/PlanCard/index.tsx
  src/components/PricingPage/ChooseYourPlan/PlanCard/styles.module.less
  src/components/PricingPage/ChooseYourPlan/utils.tsx
Labels: enhancement, generate-pr-preview

#765 Fix lottie ssr issue locally
  package.json
  patches/gatsby-plugin-loadable-components-ssr+4.3.2.patch
  src/components/Homepage/Hero/AnimatedHero.tsx
  src/components/Homepage/Hero/index.tsx
  yarn.lock
Labels: generate-pr-preview

#766 Make some SEO updates
  src/components/Footer/index.tsx
  src/components/seo.tsx
Labels: SEO, generate-pr-preview

#770 Fix animation bugged on Android devices desktop mode
  src/components/Homepage/Hero/styles.module.less
Labels: bug, generate-pr-preview

#771 Update content of 3 steps section on integration page
  src/components/Integration/ThreeQuickSteps/index.tsx
Labels: content

#767 Enable `cache` for production changes and strapi updates
  .github/workflows/deploy-preview.yml
  .github/workflows/deploy-prod.yml
  gatsby-node.ts
  package.json
  yarn.lock
Labels: generate-pr-preview

#774 Adding connector search events
  gatsby-browser.tsx
  gatsby-node.ts
  gatsby-ssr.tsx
  package.json
  src/components/Connectors/index.tsx
  src/utils.ts
Labels: generate-pr-preview

#779 Add success story banner to the comparison page
  src/components/EtlToolsXvsYPage/Comparison/index.tsx
  src/components/Layout/ReleaseBanner/styles.module.less
  src/components/SuccessStoryBanner/index.tsx
  src/components/SuccessStoryBanner/styles.module.less
  src/style.less
Labels: enhancement, generate-pr-preview

#786 Add Apache_Iceberg_Support field to comparison matrix
  gatsby-config.ts
  shared.ts
  src/components/EtlToolsXvsYPage/Comparison/UseCases/index.tsx
  src/templates/etl-tools/index.tsx
Labels: enhancement, generate-pr-preview

#789 Blog post and schema date fixes
  src/components/BlogPost/index.tsx
  src/components/CompanyUpdatesPage/ListOfUpdates/index.tsx
  src/templates/blog-post/index.tsx
  src/templates/company-update-post/index.tsx
  src/templates/success-story/index.tsx
Labels: enhancement

#797 Update URL and open in a new tab
  src/components/Layout/ReleaseBanner/index.tsx
Labels: enhancement

#796 Update Dekaf partner links
  src/components/PartnersPage/JoinPartnerProgram/index.tsx
Labels: generate-pr-preview

#792 Add expandable FAQ section with FAQ schema for blog posts
  src/components/BlogPost/Faqs/index.tsx
  src/components/BlogPost/Faqs/styles.module.less
  src/components/BlogPost/index.tsx
  src/components/BlogPost/styles.module.less
  src/components/Faq/FaqAccordions/index.tsx
  src/components/Integration/Faq/faqs.tsx
  src/components/Integration/Faq/index.tsx
  src/components/PricingPage/Faq/faqs.tsx
  src/components/PricingPage/Faq/index.tsx
  src/templates/blog-post/index.tsx
Labels: enhancement, SEO, generate-pr-preview

#799 Fix some remaining issues from FAQ PR
  src/components/BlogPost/Faqs/index.tsx
  src/components/BlogPost/index.tsx
  src/components/Integration/Faq/index.tsx
  src/components/PricingPage/Faq/index.tsx
  src/templates/blog-post/index.tsx
Labels: bug, enhancement

#790 Uncomment rss feed plugin and configure it
  gatsby-config.ts
  src/templates/blog-post/index.tsx
  src/templates/blog/index.tsx
Labels: enhancement, SEO, generate-pr-preview

#801 Update content and metadata of some pages
  src/pages/destinations.tsx
  src/pages/integrations.tsx
  src/pages/sources.tsx
Labels: SEO, generate-pr-preview

#804 Remove the unnecessary right padding of the marquee
  src/components/VanityLogosMarquee/styles.less
Labels: bug, generate-pr-preview

#807 Fix product menu icon "balance"
  src/svgs/header-balance.svg
Labels: bug

#810 Fit text and button in video
  src/components/FlowDemoVideo/styles.module.less
Labels: enhancement
