Repository estuary/marketing-site, pull requests merged in 2025-01, with the labels that each got.

#609 Comparison page improvement for seo
  src/components/EtlToolsXvsYPage/Comparison/RelatedComparisonLinks/index.tsx
  src/components/EtlToolsXvsYPage/Comparison/RelatedComparisonLinks/styles.module.less
  src/components/EtlToolsXvsYPage/Comparison/index.tsx
  src/templates/etl-tools/index.tsx
Labels: enhancement, SEO, content

#629 Filter connectors removing the Dekaf connector
  gatsby-config.ts
  gatsby-node.ts
  src/components/Connectors/index.tsx
  src/components/ConnectorsLink/index.tsx
  src/utils.ts
Labels: bug

#642 Add new SI partner Fornax
  src/components/PartnersPage/SIPartners/index.tsx
  src/images/partners-page/partner-logos/fornax.png
Labels: enhancement, content

#636 Home page updates
  src/components/Advantages/index.tsx
  src/components/DeploymentOptions/DeploymentOptionDiagram/index.tsx
  src/components/DeploymentOptions/DeploymentOptionDiagram/styles.module.less
  src/components/DeploymentOptions/styles.module.less
  src/components/DeploymentOptionsPage/ByocDeployment/index.tsx
  src/components/DeploymentOptionsPage/PrivateDeployment/index.tsx
  src/components/DeploymentOptionsPage/PublicDeployment/index.tsx
  src/components/DeploymentOptionsPage/styles.module.less
  src/components/HeaderNavbar/Resources/index.tsx
  src/components/HeaderNavbar/Resources/items.tsx
  src/components/HeaderNavbar/index.tsx
  src/components/HeroSectionActions/RegisterCta.tsx
  src/components/HeroSectionActions/index.tsx
  src/components/Homepage/AutomateDataops/index.tsx
  src/components/Homepage/BuildInMinutes/index.tsx
  src/components/Homepage/DeploymentModes/index.tsx
  src/components/Homepage/Do4xMoreWith25xLess/index.tsx
  src/components/Homepage/Hero/index.tsx
  src/components/Homepage/Hero/styles.module.less
  src/components/Homepage/InnovateFaster/index.tsx
  src/components/Homepage/InnovateFaster/styles.module.less
  src/components/Homepage/MoveAndTransform/index.tsx
  src/components/Homepage/MoveAndTransform/styles.module.less
  src/components/Homepage/TheBestRealTimeCdc/index.tsx
  src/components/MetricCard/index.tsx
  src/components/MetricCard/styles.module.less
  src/components/SecurityCertificates/index.tsx
  src/components/SeeHowSection/index.tsx
  src/images/flow-mobile.png
  src/images/homepage/move-and-transform-data-mobile.png
  src/images/homepage/move-and-transform-data.png
  src/pages/index.tsx
  src/svgs/capture.svg
  src/svgs/homepage/ai.svg
  src/svgs/homepage/analytics.svg
  src/svgs/homepage/batch.svg
  src/svgs/homepage/ops.svg
  src/svgs/homepage/real-time.svg
  src/svgs/homepage/saas.svg
  src/svgs/homepage/store.svg
  src/svgs/homepage/transform.svg
  src/svgs/real-time-delivery.svg
  src/svgs/store-and-transform.svg
Labels: enhancement, content

#648 Adapt Flow diagram component to company updates hero section
  src/components/CompanyUpdatesPage/Hero/index.tsx
  src/components/CompanyUpdatesPage/Hero/styles.module.less
  src/components/FlowDiagram/index.tsx
  src/components/FlowDiagram/styles.module.less
  src/components/Homepage/MoveAndTransform/index.tsx
  src/components/Homepage/MoveAndTransform/styles.module.less
Labels: enhancement, content

#653 Small homepage updates
  src/components/DeploymentOptions/DeploymentOptionDiagram/styles.module.less
  src/components/DeploymentOptions/Tabs/index.tsx
  src/components/DeploymentOptions/index.tsx
  src/components/DeploymentOptions/styles.module.less
  src/components/DeploymentOptionsPage/styles.module.less
  src/components/FlowDemoVideo/index.tsx
  src/components/FlowDemoVideo/styles.module.less
  src/components/Homepage/AutomateDataops/index.tsx
  src/components/Homepage/MoveAndTransform/index.tsx
  src/components/SeeHowSection/index.tsx
  src/components/SeeHowSection/styles.module.less
Labels: enhancement, content

#660 Undo some homepage updates
  src/components/Homepage/Hero/index.tsx
  src/components/Homepage/InnovateFaster/index.tsx
  src/components/Homepage/InnovateFaster/styles.module.less
  src/components/Homepage/TheBestRealTimeCdc/index.tsx
  src/pages/index.tsx
Labels: enhancement, SEO, content
